# Generated by Django 4.2.15 on 2024-09-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_genre_genre_num_alter_author_date_of_death'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_num',
            new_name='genre_id',
        ),
    ]
